[tools]
darklua = { github = "seaofvoices/darklua", version = "=0.17.3" }
luau-lsp = { github = "JohnnyMorganz/luau-lsp", version = "=1.59.0" }
lune = { github = "lune-org/lune", version = "=0.10.4" }
rojo = { github = "rojo-rbx/rojo", version = "=7.6.1" }
selene = { github = "Kampfkarren/selene", version = "=0.29.0" }
stylua = { github = "JohnnyMorganz/StyLua", version = "=2.3.1" }
wally = { github = "UpliftGames/wally", version = "=0.3.2" }
